repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-yaml
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: []
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        # Temporarily disable until scripts path is stabilized
        stages: [manual]
        args: []
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        # Temporarily disable pytest in pre-commit
        stages: [manual]
        entry: python -m pytest -q -m "not integration"
        language: system
        pass_filenames: false
        types: [python]
